# -*- coding: utf-8 -*-
"""合約產生器後端

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1539WVKXuiYKXD5PYqan4Ntw1H5h3qNff
"""

from flask import Flask, render_template, request, send_file
from docxtpl import DocxTemplate
import io
import zipfile
import re
import os

app = Flask(__name__)

# --- 核心功能：Word XML 強力清洗引擎 ---
def clean_word_xml(doc_path):
    """
    讀取 Word 檔，直接修改內部的 document.xml，
    移除拼字檢查標記、合併被切斷的標籤。
    """
    # 1. 將 docx 解壓到記憶體
    with open(doc_path, 'rb') as f:
        docx_bytes = f.read()

    bio_in = io.BytesIO(docx_bytes)
    bio_out = io.BytesIO()

    with zipfile.ZipFile(bio_in, 'r') as zin:
        with zipfile.ZipFile(bio_out, 'w') as zout:
            for item in zin.infolist():
                content = zin.read(item.filename)

                if item.filename == 'word/document.xml':
                    xml_str = content.decode('utf-8')

                    # A. 移除 Word 的校對標記 (Proof Errors, Grammar Errors) - 這是最大兇手
                    xml_str = re.sub(r'<w:proofErr[^>]*/>', '', xml_str)
                    xml_str = re.sub(r'<w:gramE[^>]*/>', '', xml_str)
                    xml_str = re.sub(r'<w:lang[^>]*/>', '', xml_str)

                    # B. 移除刪除線內容 (Track Changes Deletions)
                    xml_str = re.sub(r'<w:del[^>]*>.*?</w:del>', '', xml_str, flags=re.DOTALL)

                    # C. 移除插入標記殼 (Track Changes Insertions) - 保留內容
                    xml_str = re.sub(r'<w:ins[^>]*>', '', xml_str)
                    xml_str = re.sub(r'</w:ins>', '', xml_str)

                    # D. 合併被切斷的標籤 (Duplicate Open Tags 修復)
                    # 把 <w:t>{</w:t>...雜訊...<w:t>{</w:t> 變成 <w:t>{{</w:t>
                    # 這是一個簡化的正則表達式，處理常見的斷裂
                    xml_str = re.sub(r'<w:t>({)</w:t>.*?<w:t>({)</w:t>', '<w:t>{{</w:t>', xml_str, flags=re.DOTALL)
                    xml_str = re.sub(r'<w:t>(})</w:t>.*?<w:t>(})</w:t>', '<w:t>}}</w:t>', xml_str, flags=re.DOTALL)

                    content = xml_str.encode('utf-8')

                zout.writestr(item, content)

    bio_out.seek(0)
    return bio_out

@app.route('/')
def home():
    return render_template('index.html')

@app.route('/generate', methods=['POST'])
def generate():
    try:
        data = request.json

        # 1. 先進行清洗 (這是 JS 做不到的)
        cleaned_docx = clean_word_xml("template.docx")

        # 2. 載入清洗後的範本
        doc = DocxTemplate(cleaned_docx)

        # 3. 渲染變數
        doc.render(data)

        # 4. 輸出
        output = io.BytesIO()
        doc.save(output)
        output.seek(0)

        filename = f"東海大學實習合約_{data.get('s1_name', 'student')}.docx"

        return send_file(
            output,
            as_attachment=True,
            download_name=filename,
            mimetype='application/vnd.openxmlformats-officedocument.wordprocessingml.document'
        )

    except Exception as e:
        return str(e), 500

if __name__ == '__main__':
    port = int(os.environ.get("PORT", 5000))
    app.run(host='0.0.0.0', port=port)