# -*- coding: utf-8 -*-
"""合約產生器

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AbDIg7N9-2UysC5N90zAo84uv5G23v_i
"""

import streamlit as st
from docxtpl import DocxTemplate
import io
from datetime import datetime

# --- 1. 頁面設定 ---
st.set_page_config(page_title="東海大學實習合約產生系統", page_icon="🎓", layout="centered")

st.markdown("""
    <style>
    .main-header {
        color: #002E5D;
        font-weight: bold;
        text-align: center;
        padding-bottom: 20px;
        border-bottom: 3px solid #C6A87C;
        margin-bottom: 20px;
    }
    .section-card {
        background-color: #f8f9fa;
        padding: 20px;
        border-radius: 10px;
        border-left: 5px solid #002E5D;
        margin-bottom: 20px;
        box-shadow: 0 2px 4px rgba(0,0,0,0.1);
    }
    .stButton>button {
        width: 100%;
        background-color: #002E5D;
        color: white;
        font-weight: bold;
    }
    </style>
""", unsafe_allow_html=True)

st.markdown("<h1 class='main-header'>🎓 東海大學學生校外實習合約產生系統</h1>", unsafe_allow_html=True)

# 準備資料容器
context = {}

# --- 2. 實習機構資料區 ---
st.markdown("<div class='section-card'><h3>🏢 乙方：實習機構資料</h3>", unsafe_allow_html=True)
col_c1, col_c2 = st.columns(2)
with col_c1:
    company_name = st.text_input("機構全銜 (法定名稱)", placeholder="例：國泰世華商業銀行股份有限公司")
    company_rep = st.text_input("代表人姓名")
    company_title = st.text_input("代表人職稱", value="負責人") # 新增欄位
with col_c2:
    company_tax_id = st.text_input("統一編號")

st.markdown("---")
reg_address = st.text_input("公司登記地址")
is_branch = st.checkbox("實習地點與登記地址不同 (如派駐分公司)")

if is_branch:
    branch_name = st.text_input("實習單位/分公司名稱", placeholder="例：西屯分公司")
    branch_address = st.text_input("實際實習地址")
    final_address = f"{reg_address} (實習地點：{branch_name} - {branch_address})"
else:
    final_address = reg_address
st.markdown("</div>", unsafe_allow_html=True)

# --- 3. 學生資料區 (多人處理邏輯) ---
st.markdown("<div class='section-card'><h3>🧑‍🎓 甲方：學生資料</h3>", unsafe_allow_html=True)

# 讓使用者選擇人數
student_count = st.number_input("本合約包含幾位學生？", min_value=1, max_value=3, value=1)
student_list = []

for i in range(student_count):
    st.markdown(f"**學生 {i+1}**")
    col_s1, col_s2 = st.columns(2)
    with col_s1:
        s_name = st.text_input(f"姓名 ({i+1})", key=f"s_name_{i}")
    with col_s2:
        s_id = st.text_input(f"系級/學號 ({i+1})", key=f"s_id_{i}")
    student_list.append({'name': s_name, 'id': s_id})

# 補齊 3 人空位 (防呆，避免 Word 變數報錯)
while len(student_list) < 3:
    student_list.append({'name': "", 'id': ""})

st.markdown("</div>", unsafe_allow_html=True)

# --- 4. 實習條件與待遇 (核心邏輯) ---
st.markdown("<div class='section-card'><h3>📝 實習條件與待遇</h3>", unsafe_allow_html=True)

contract_type = st.radio("實習類型：", ("一般型 (學習型)", "工作型 (勞資型)"), horizontal=True)

# 日期處理
col_d1, col_d2 = st.columns(2)
with col_d1:
    s_date = st.date_input("開始日期")
    s_y, s_m, s_d = s_date.year - 1911, s_date.month, s_date.day
with col_d2:
    e_date = st.date_input("結束日期")
    e_y, e_m, e_d = e_date.year - 1911, e_date.month, e_date.day

# 時間處理
col_t1, col_t2, col_t3 = st.columns(3)
with col_t1:
    daily_start = st.time_input("每日開始", value=datetime.strptime("09:00", "%H:%M"))
with col_t2:
    daily_end = st.time_input("每日結束", value=datetime.strptime("18:00", "%H:%M"))
with col_t3:
    daily_hours = st.number_input("每日時數", value=8.0, step=0.5)

st.markdown("---")

# 第八條：待遇邏輯 (Checkbox Logic)
# 預設全空
context.update({
    'type_learn_check': '□', 'type_work_check': '□',
    'chk_pay_none': '□', 'chk_pay_scholar': '□', 'chk_pay_allowance': '□',
    'pay_learn_amount': "", 'pay_work_amount': ""
})

if contract_type == "一般型 (學習型)":
    context['type_learn_check'] = '☑'
    st.success("✅ 學習型：請設定給付項目")

    pay_opt = st.radio("給付項目", ["無", "獎學金", "實習津貼"], horizontal=True)

    if pay_opt == "無":
        context['chk_pay_none'] = '☑'
        context['pay_learn_amount'] = "0"
    elif pay_opt == "獎學金":
        context['chk_pay_scholar'] = '☑'
        amt = st.number_input("獎學金總額", min_value=0, step=1000)
        context['pay_learn_amount'] = f"{amt:,}"
    else: # 實習津貼
        context['chk_pay_allowance'] = '☑'
        amt = st.number_input("津貼總額", min_value=0, step=1000)
        context['pay_learn_amount'] = f"{amt:,}"

else: # 勞資型
    context['type_work_check'] = '☑'
    st.warning("⚠️ 勞資型：請設定薪資")
    pay_work_amt = st.number_input("月薪金額", min_value=27470, step=100)
    context['pay_work_amount'] = f"{pay_work_amt:,}"

st.markdown("</div>", unsafe_allow_html=True)

# --- 5. 福利 (第十條) ---
st.markdown("<div class='section-card'><h3>🎁 福利項目</h3>", unsafe_allow_html=True)

def welfare_logic(label, key_prefix, unit):
    """處理福利的勾選邏輯 Helper Function"""
    opt = st.selectbox(label, ["無", "免費提供", "付費提供"], key=key_prefix)
    cost = ""

    # 預設全空
    checks = {f'chk_{key_prefix}_none': '□', f'chk_{key_prefix}_free': '□', f'chk_{key_prefix}_paid': '□'}

    if opt == "無":
        checks[f'chk_{key_prefix}_none'] = '☑'
    elif opt == "免費提供":
        checks[f'chk_{key_prefix}_free'] = '☑'
    else: # 付費提供
        checks[f'chk_{key_prefix}_paid'] = '☑'
        val = st.number_input(f"{label}費用 ({unit})", min_value=0, step=100, key=f"{key_prefix}_cost")
        cost = f"{val:,}"

    return checks, cost

col_w1, col_w2, col_w3 = st.columns(3)

with col_w1:
    dorm_checks, dorm_cost = welfare_logic("住宿", "dorm", "元/月")
with col_w2:
    food_checks, food_cost = welfare_logic("膳食", "food", "元/餐")
with col_w3:
    # 交通比較特別，有「交通津貼」選項，這裡簡化為與合約一致的三選項，或需特規處理
    trans_opt = st.selectbox("交通", ["無", "免費提供", "付費提供"], key="trans")
    trans_cost = ""
    trans_checks = {'chk_trans_none': '□', 'chk_trans_free': '□', 'chk_trans_paid': '□'}

    if trans_opt == "無":
        trans_checks['chk_trans_none'] = '☑'
    elif trans_opt == "免費提供":
        trans_checks['chk_trans_free'] = '☑'
    else:
        trans_checks['chk_trans_paid'] = '☑'
        val = st.number_input("交通費用 ({元/月})", min_value=0, step=100, key="trans_cost_input")
        trans_cost = f"{val:,}"

# 將福利變數寫入 context
context.update(dorm_checks)
context.update({'dorm_cost': dorm_cost})
context.update(food_checks)
context.update({'food_cost': food_cost})
context.update(trans_checks)
context.update({'trans_cost': trans_cost})

st.markdown("</div>", unsafe_allow_html=True)

# --- 6. 產生按鈕 ---
if st.button("🚀 產生合約文件 (Word)"):
    if not company_name or not student_list[0]['name']:
        st.error("❌ 機構名稱與第一位學生姓名為必填")
    else:
        # 填入基本資料
        context.update({
            'company_name': company_name,
            'company_tax_id': company_tax_id,
            'company_rep': company_rep,
            'company_title': company_title,
            'company_address': final_address,

            # 學生資料 (填入 s1, s2, s3)
            's1_name': student_list[0]['name'], 's1_id': student_list[0]['id'],
            's2_name': student_list[1]['name'], 's2_id': student_list[1]['id'],
            's3_name': student_list[2]['name'], 's3_id': student_list[2]['id'],
            # 為了立合約書人那一欄 (通常只列第一位或全列，這裡預設全列)
            'student_name': student_list[0]['name'] + (" 等" if student_count > 1 else ""),

            # 日期時間
            's_y': s_y, 's_m': s_m, 's_d': s_d,
            'e_y': e_y, 'e_m': e_m, 'e_d': e_d,
            'daily_start': daily_start.strftime("%H:%M"),
            'daily_end': daily_end.strftime("%H:%M"),
            'daily_hours': daily_hours,
        })

        try:
            doc = DocxTemplate("template.docx")
            doc.render(context)
            bio = io.BytesIO()
            doc.save(bio)

            file_name = f"東海大學實習合約_{student_list[0]['name']}_{company_name}.docx"
            st.download_button("📥 下載合約", bio.getvalue(), file_name, "application/vnd.openxmlformats-officedocument.wordprocessingml.document")
            st.success("✅ 檔案已建立！")

        except Exception as e:
            st.error(f"❌ 錯誤：{e} (請確認 template.docx 是否存在且標籤正確)")